config/routes.rb
Rails.application.routes.draw do
  get 'forecasts/index'
  get 'forecasts/show'
  root 'forecasts#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/forecasts_controller.rb
require 'forecast'

class ForecastsController < ApplicationController
  def index
  end

  def show
    @forecasts = Forecast.new(params[:forecast])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forecasts_helper.rb
module ForecastsHelper
end

app/views/forecasts/_current.html.erb
<div class="col-md-8">
  <h1>The weather in <%= @forecasts.current['name'] %>, <%= @forecasts.current['sys']['country'] %></h1>
  <p>
    <span class="lead"><%= @forecasts.current['weather'][0]['main'] %></span>&nbsp;
    <small>(<%= @forecasts.current['weather'][0]['description'] %>)</small>
  </p>
</div>
<div class="col-md-4">
  <dl class="row">
    <dt class="col-sm-4">Temperature:</dt>
    <dd class="col-sm-8"><%= @forecasts.current['main']['temp'] %> C</dd>

    <dt class="col-sm-4">Humidity:</dt>
    <dd class="col-sm-8"><%= @forecasts.current['main']['humidity'] %> %</dd>

    <dt class="col-sm-4">Pressure:</dt>
    <dd class="col-sm-8"><%= @forecasts.current['main']['pressure'] %> Millibars</dd>

    <dt class="col-sm-4">Wind:</dt>
    <dd class="col-sm-8"><%= @forecasts.current['wind']['speed'] %></dd>
  </dl>
</div>

app/views/forecasts/_weekly.html.erb
<h3>Week's forecast</h3>

app/views/forecasts/index.html.erb
<h1>Forecasts#index</h1>
<p>Find me in app/views/forecasts/index.html.erb</p>

app/views/forecasts/show.html.erb
<div class="jumbotron">
  <div class="row">
    <%= render 'current' %>
  </div>
</div>
<p><%# @forecasts.current.inspect %></p>

<%= render 'weekly' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiWeather</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <div class="container">
        <%= link_to 'ApiWeather', root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
          <%= form_for :forecast, url: forecasts_show_path, method: 'GET', html: { class: 'form-inline my-2 my-lg-0' } do |f| %>
            <%= f.text_field :location, class: 'form-control mr-sm-2', placeholder: 'Search for location ...' %>
            <%= f.submit 'Go!', class: 'btn btn-outline-success my-2 my-sm-0' %>
          <% end %>
        </div>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>

    <footer class="footer">
      <div class="container">
        <span class="text-muted">
          Developed by <a href="mailto:LykourgosTs@hotmail.com">Lykourgos Tsirikos</a>
        </span>
      </div>
    </footer>
  </body>
</html>